{% set version = "0.3.0" %}

package:
  name: dask-ec2
  version: "{{ version }}"

source:
  fn: dask-ec2-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/d/dask-ec2/dask-ec2-{{ version }}.tar.gz
  md5: 1025ffbe377540a125c5abba3b4f4ba0

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - dask-ec2=dask_ec2.cli.main:start

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - six
    - click
    - paramiko
    - boto3
    - pyyaml

test:
  imports:
    - dask_ec2
    - dask_ec2.cli
    - dask_ec2.tests
    - dask_ec2.tests.salt
  commands:
    - dask-ec2 --help

about:
  home: https://github.com/dask/dask-ec2
  license: Apache 2.0
  summary: 'Start a cluster in EC2 for dask.distributed'

extra:
  recipe-maintainers:
    - danielfrg
    - koverholt
