travis:
  secure:
    BINSTAR_TOKEN: r673ODHuSiD4nq69O4wgtA/0reuxMo8nVpkjiw2bT3M7c8UYqMSZx6mlAZqYWNOpnEg/ACk0Vk5K4hsVA1MmyRou1lDPjQ5TFjzcMt2/MlHu4Y8KP1CS2FxHrghMyzoCUeXs+GPEXs4SLrfn3hy42eVwcIiiI0TeqxEZyzx6LbeepbiDCFMz1CDty5LvtsHeUatcT72NNmUuDwNILh3Elqiz/cnFb0Q8B6Ol9s9X7mowHouqH87OilmIVl1L44KWC6AGXfOvbxQ8aSHxEBYg9ITfFnPPbYk53vrSNUGsFzsxlXKR95Kn99Pn1rvyTYO+gjD/5r1RFqCmjAqcglMr1cDasbkixx+g37ggTAUOYr0bFhikmt4Lj1JB0DB5NQwvhO6wbjimqbDV5OnwUKavPZVU2luHt5kDd6u92y5GiZ4DETaJ5OJDpAZH/lFVSciQix9+mFEAnEUhlgY018TY+zvkCoYfDE/bgYuMdGlho+V0LcBsj3rZLLpz5n0WCknp0ezN/lQQLfm3ZzhwI/5ko3velKmzT9Zu8B1U6aW2AnJUxiBU6TcUeEyhztvyR85eF1kWnujGwrwCQ2k3gPGb5HpZFfxuXgz1oZvdFXjsOZD8VuKWtfigyvjzo1v46ZD30NlTpBWjqtCbA4QrPCfXv2Kyr1xkRURI6aXatarbW7E=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
