travis:
  secure:
    BINSTAR_TOKEN: jOwYJm0YgdvdXj5Cr8/LQceclDPH4H83pXjqAjigjatUSxX7umPuJzpv5OHzR1ni+FLOfCRuZNwDZzV/MPIiM9CSMyhLfoYmhs5NQ8OX/t74QB4SQp+CU6vVKRykIVTm8CLd/np3Rq9J/iah9XtxBpdTtQ4RUW5zg5iKQafPhmhI8QnHHe5eF++SMcmmEALgR/QWFPBwgFTVJWMxf0NfNTCEZh+O+/DJoxyCOHX+qpbyAzL/1UkLta1100Zhazg1b6xl8arpgJbTZs9yoWNKSYyREy3yiwb07wcxwrXGjtbheASYGT7zaybIjRoHWeajeib9C30ilxVTWVoyvmS2gMHT5/cCs9OjAKYd4zJJZxrUs2fqEy1kBd6R/x89phnfV+yIgCEw2kgFXXVvnQcI4gxAxRYfWiX+/9OlodGCsJIgO10XTT7upsnOdt5YkqWMFMKQAnWYnwV4Wvsw7T8JZsM2kiGRWNRwJFkQhzJ4EuEPLBeKK69Vx8Sd0rKpYhovTRmvc+uodQtmfVwWyK3F82iWsnCRcvqxREPkJ4mbmvL26enEqKxafBN7ytI60LcOdeNvoYQFPr+a3QUhw/84RCKcZiAUAvyiDpneXcLvNnMPVRyXc8mZt/Iq+2j2vuz+wEFhtJ9uUscU/VI+DHsaC0EvE6wErBX9t7MMaVUMBu4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
